export const mockResponse = (env: string) => ({
  status: "UP",
  responseDateTime: new Date().toISOString(),
  components: {
    Apigee: {
      status: "UP",
      details: {
        proxy: {
          name: `${env}-proxy`,
          release: "1.2.3",
          revision: "42",
          status: "UP",
        },
      },
    },
    backends: {
      status: "UP",
      details: {
        // IR
        IR_Gemini: {
          serviceUri: `https://${env}.example.com/ir-gemini`,
          responseDateTime: new Date().toISOString(),
          StatusCode: "200",
          ReasonPhrase: "OK",
          status: "UP",
          statusMessage: "Service is running",
          "swagger-version": "2.0",
        },
        IR_Centaurus: {
          serviceUri: `https://${env}.example.com/ir-centaurus`,
          responseDateTime: new Date().toISOString(),
          StatusCode: "503",
          ReasonPhrase: "Service Unavailable",
          status: "DOWN",
          statusMessage: "Connection refused",
          "swagger-version": "2.0",
        },
        IR_Andromeda: {
          serviceUri: `https://${env}.example.com/ir-andromeda`,
          responseDateTime: new Date().toISOString(),
          StatusCode: "200",
          ReasonPhrase: "OK",
          status: "UP",
          statusMessage: "Service is running",
          "swagger-version": "2.0",
        },
        // IBO
        IBO_Gemini: {
          serviceUri: `https://${env}.example.com/ibo-gemini`,
          responseDateTime: new Date().toISOString(),
          StatusCode: "200",
          ReasonPhrase: "OK",
          status: "UP",
          statusMessage: "Service is running",
          "swagger-version": "2.0",
        },
        IBO_Centaurus: {
          serviceUri: `https://${env}.example.com/ibo-centaurus`,
          responseDateTime: new Date().toISOString(),
          StatusCode: "200",
          ReasonPhrase: "OK",
          status: "UP",
          statusMessage: "Service is running",
          "swagger-version": "2.0",
        },
        IBO_Andromeda: {
          serviceUri: `https://${env}.example.com/ibo-andromeda`,
          responseDateTime: new Date().toISOString(),
          StatusCode: "504",
          ReasonPhrase: "Gateway Timeout",
          status: "DOWN",
          statusMessage: "Upstream timeout",
          "swagger-version": "2.0",
        },
        // IssuerGW
        IssuerGW_Gemini: {
          serviceUri: `https://${env}.example.com/issuergw-gemini`,
          responseDateTime: new Date().toISOString(),
          StatusCode: "200",
          ReasonPhrase: "OK",
          status: "UP",
          statusMessage: "Service is running",
          "swagger-version": "2.0",
        },
        IssuerGW_Centaurus: {
          serviceUri: `https://${env}.example.com/issuergw-centaurus`,
          responseDateTime: new Date().toISOString(),
          StatusCode: "200",
          ReasonPhrase: "OK",
          status: "UP",
          statusMessage: "Service is running",
          "swagger-version": "2.0",
        },
        IssuerGW_Andromeda: {
          serviceUri: `https://${env}.example.com/issuergw-andromeda`,
          responseDateTime: new Date().toISOString(),
          StatusCode: "200",
          ReasonPhrase: "OK",
          status: "UP",
          statusMessage: "Service is running",
          "swagger-version": "2.0",
        },
        // wlp-fo-siboi
        "wlp-fo-siboi-gemini": {
          serviceUri: `https://${env}.example.com/wlp-fo-siboi-gemini`,
          responseDateTime: new Date().toISOString(),
          StatusCode: "200",
          ReasonPhrase: "OK",
          status: "UP",
          statusMessage: "Service is running",
          "swagger-version": "2.0",
        },
        "wlp-fo-siboi-copernicus": {
          serviceUri: `https://${env}.example.com/wlp-fo-siboi-copernicus`,
          responseDateTime: new Date().toISOString(),
          StatusCode: "500",
          ReasonPhrase: "Internal Server Error",
          status: "DOWN",
          statusMessage: "Unexpected error",
          "swagger-version": "2.0",
        },
        "wlp-fo-siboi-davinci": {
          serviceUri: `https://${env}.example.com/wlp-fo-siboi-davinci`,
          responseDateTime: new Date().toISOString(),
          StatusCode: "200",
          ReasonPhrase: "OK",
          status: "UP",
          statusMessage: "Service is running",
          "swagger-version": "2.0",
        },
        // Ungrouped
        "auth-service": {
          serviceUri: `https://${env}.example.com/auth`,
          responseDateTime: new Date().toISOString(),
          StatusCode: "200",
          ReasonPhrase: "OK",
          status: "UP",
          statusMessage: "Service is running",
          "swagger-version": "2.0",
        },
      },
    },
  },
});
